name: vizdoom-tf2-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.2
  - notebook
  - jupyter_contrib_nbextensions
  - numpy
  - pandas
  - matplotlib
  - gym
  - opencv
  - pydot
  - cudatoolkit=10.1
  - pip
  - pip:
    - tensorflow-gpu==2.3.0
