name: vizdoom
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - notebook
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scikit-image
  - tensorflow==2.3.0
  - gym
  - vizdoom
  - opencv
  - ipywidgets
  - pydot
